Repository 1crowie1/stock-project, pull requests merged in 2022-07, with the labels that each got.

#31 Harrison/backend
  data-pipeline/load.py
  requirements.txt
Labels: enhancement, feature, system

#32 Update twitter scraper to take variable input
  stock-scraper/scrape_twitter.py
Labels: enhancement

#36 Harrison/data pipeline
  algo-trader/trade.py
  data-pipeline/load.py
  data-pipeline/transform.py
  stock-scraper/dump.py
Labels: feature

#37 #35; Function setup for transforming scrapped subreddit data
  stock-scraper/scrape_reddit.py
Labels: enhancement

#38 File structure change, pipeline improvements
  data-pipeline/extract.py
  data-pipeline/scrape_reddit.py
  data-pipeline/scrape_twitter.py
Labels: enhancement, feature, system

#39 Change Scrape to JSON
  data-pipeline/scrape_twitter.py
  data-pipeline/stock_data_api.py
Labels: feature
